/**
 * This file was generated by the Jeddict
 */
package CompanyEntity.entity;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * @author mehtab
 */
@Entity
@XmlRootElement
public class Company {

    public Company() {
    }

    public Company(String Name) {
        this.Name = Name;
    }

    public Company(Integer id, String Name) {
        this.id = id;
        this.Name = Name;
    }

    public Company(Integer id, String Name, List<Employee> employees) {
        this.id = id;
        this.Name = Name;
        this.employees = employees;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Basic
    private String Name;

    @OneToMany
    private List<Employee> employees;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    @XmlTransient
    public List<Employee> getEmployees() {
        if (employees == null) {
            employees = new ArrayList<>();
        }
        return this.employees;
    }

    public void setEmployees(List<Employee> employees) {
        this.employees = employees;
    }

    public void addEmployee(Employee employee) {
        getEmployees().add(employee);
    }

    public void removeEmployee(Employee employee) {
        getEmployees().remove(employee);
    }

}
