/**
 * This file was generated by the Jeddict
 */
package CompanyEntity.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author mehtab
 */
@Entity
@XmlRootElement
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Basic
    private String Name;

    private Integer companyId;

    public Employee() {
    }

    public Employee(Integer id, String Name) {
        this.id = id;
        this.Name = Name;
    }
    

    public Employee(Integer id, String Name, Integer companyId) {
        this.id = id;
        this.Name = Name;
        this.companyId = companyId;
    }

    public Employee(String Name) {
        this.Name = Name;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

}
